# Generated by Django 2.1.7 on 2019-12-22 06:01

from django.db import migrations, models
import django.db.models.deletion
import restaurant_menu.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наменование')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наменование')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('calorie_content', models.FloatField(verbose_name='Калорийность')),
                ('image', models.ImageField(blank=True, max_length=256, upload_to=restaurant_menu.utils.dich_image_path, verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наменование')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant_menu.DishCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='allergen',
            name='dish',
            field=models.ManyToManyField(related_name='allergens', to='restaurant_menu.Dish', verbose_name='Аллерген'),
        ),
    ]
